export type PlayerDayState = {
  user_id: string;
  day_index: number;
  energy: number;
  stress: number;
  money: number;
  study_progress: number;
  social_capital: number;
  health: number;
  total_study: number;
  total_work: number;
  total_social: number;
  total_health: number;
  total_fun: number;
  allocation_hash?: string | null;
  pre_allocation_energy?: number | null;
  pre_allocation_stress?: number | null;
  pre_allocation_money?: number | null;
  pre_allocation_study_progress?: number | null;
  pre_allocation_social_capital?: number | null;
  pre_allocation_health?: number | null;
  resolved_at?: string | null;
  end_energy?: number | null;
  end_stress?: number | null;
  next_energy?: number | null;
  next_stress?: number | null;
  created_at: string;
  updated_at: string;
};
